### PR TITLE
ENH:  Add automated AIF mask generation.

### PR DESCRIPTION
**Pull request by ntustison**
Previously, the function ``bloodPerfusionSVD`` required an arterial input function (AIF) mask image to generate the CBF, etc. images.  This commit adds the ability to automatically generate a mask using this [approach](https://www.ncbi.nlm.nih.gov/pubmed/15956519).

### CODE REVIEW

**Comment by ntustison** [comment]
Hey @stnava , this is the only commit I need before we can process the perfusion data.  It's basically just a couple lines to process a single data set:

```
perfusionImage <- antsImageRead( perfusionFile )
voiMaskImage <- antsImageRead( brainMaskFile )

perfusion <- bloodPerfusionSVD( perfusionImage, voiMaskImage, thresholdSVD = 0.2, deltaTime = 1.0 )

antsImageWrite( perfusion$cbfImage, "cbfImage.nii.gz" )
antsImageWrite( perfusion$cbvImage, "cbvImage.nii.gz" )
antsImageWrite( perfusion$mttImage, "mttImage.nii.gz" )
```

but I've also added some visualization capabilities which I'll demonstrate in the example I'll send you after this gets merged.

**Comment by muschellij2** [comment]
Weird - seeing failures on https://travis-ci.org/muschellij2/ANTsR/jobs/642453185#L10273 and https://travis-ci.org/ANTsX/ANTsR/jobs/641895019#L10206

**Comment by ntustison** [comment]
@muschellij2 Yeah, thanks for taking a look.  I'm at a loss as to why those failures are occurring with this pull request.

**Comment by stnava** [comment]
sorry - I am stretched pretty thin til something like the 6th of February
but might be able to look closer this upcoming weekend.

brian

**Comment by ntustison** [comment]
@stnava --- No urgency as I just pulled this branch to the local machine for processing the breacher data.  Whenever you can is fine.

**Pull request closed without merging**
