### PR TITLE
ENH:  Pull request branch for histogramMatchImage.

### PR DESCRIPTION
**Pull request by ntustison**

### CODE REVIEW

**Comment by stnava** [comment]
just one comment  -  might be better in antsrcore b/c antsr is up against build time limits ... but we have extra time in antsrcore ... am trying to rebuild now on travis so will see if it goes through this time.... we can also request extra time in antsr but not sure when we would get that.

**Comment by stnava** [comment]
looks like time may not be an issue but there is an error:

```
* checking examples ... ERROR
Running examples in â€˜ANTsR-Ex.Râ€™ failed
The error most likely occurred in:

> base::assign(".ptime", proc.time(), pos = "CheckExEnv")
> ### Name: histogramMatchImage
> ### Title: histogramMatchImage
> ### Aliases: histogramMatchImage
> 
> ### ** Examples
> 
> sourceImage <- antsImageRead( getANTsRData( "r16" ), 2 )
> referenceImage <- antsImageRead( getANTsRData( "r64" ), 2 )
> matchedImage <- histogramMatchImageFilter( sourceImage, referenceImage )
Error in histogramMatchImageFilter(sourceImage, referenceImage) : 
  could not find function "histogramMatchImageFilter"
Execution halted
```

**Comment by ntustison** [comment]
Sorry, Brian.  Forgot to run ``roxygenize()`` after fixing a small bug.

**Comment by ntustison** [comment]
Thanks @stnava

**Pull request merged**
