### PR TITLE
This should build binaries like ITKR and ANTsRCore

### PR DESCRIPTION
**Pull request by muschellij2**
I version bumped to tag and build but realized I don't have push access to this repo.  This should now build binaries with the R-version embedded in the names similar to `ITKR` and `ANTsRCore`.

### CODE REVIEW

**Comment by muschellij2** [comment]
OK @stnava, given https://travis-ci.org/muschellij2/ANTsR/builds/425469943,  this looks like it can be merged.  The big difference is the `hdf5r` functionality, which doesn't require that the `h5` get a data.matrix but can pass in a `data.frame` and also how thing are referenced and read in.  Other `Rd` files are simply changed because of new roxygen, but all whitespace crap.   All travis changes are to make sure all this stuff finally builds on the backend.

**Comment by muschellij2** [comment]
Weird I'm getting a failure here, but getting pass on mine: https://travis-ci.org/muschellij2/ANTsR/builds/425557716

**Comment by stnava** [comment]
ah ... there is an easy alternative that i know works for rflann which is this:

https://cran.r-project.org/web/packages/devtools/vignettes/dependencies.html

may also work for mfilter but we can switch to h5r, no worries.

**Comment by stnava** [comment]
oops i see you've already implemented this - thx

**Comment by stnava** [comment]
it was just a time out on osx - i will merge and we can revisit the timing issue if needed

**Comment by muschellij2** [comment]
I think we should email contact@travis-ci.org or support@travis-ci.org to
ask for 120 minutes to solve this issue like we did with ANTsRCore.

**Pull request merged**
